// GENERATED by generate_deck_header.py -- do not edit.
// Source deck: /home/maorm/branson/run/hohlraum_cp_regime.xml
#ifndef STORM_BRANSON_DECK_HPP
#define STORM_BRANSON_DECK_HPP
#include <array>
#include <cstddef>
namespace BransonDeck {
// Branson units: cm, keV, shake (1e-8 s), jerk (1e16 erg).
inline constexpr std::size_t nx = 65, ny = 65, nz = 140;
inline constexpr double cellWidth = 0.01;
inline constexpr double xLo = 0.0, xHi = 0.65;
inline constexpr double yLo = 0.0, yHi = 0.65;
inline constexpr double zLo = 0.0, zHi = 1.4;
inline constexpr double dtShakes = 0.001;
inline constexpr double tStopShakes = 0.005;
inline constexpr double tStartShakes = 0.0;
inline constexpr long long photons = 52900000;
struct Division { double lo, hi; std::size_t cells; };
inline constexpr std::array<Division, 3> xDiv = {{{0.0, 0.4, 40}, {0.4, 0.6, 20}, {0.6, 0.65, 5}}};
inline constexpr std::array<Division, 3> yDiv = {{{0.0, 0.4, 40}, {0.4, 0.6, 20}, {0.6, 0.65, 5}}};
inline constexpr std::array<Division, 6> zDiv = {{{0.0, 0.1, 10}, {0.1, 0.15, 5}, {0.15, 0.55, 40}, {0.55, 0.95, 40}, {0.95, 1.35, 40}, {1.35, 1.4, 5}}};
struct Region { int id; double density, CV, opacA, opacB, opacC, opacS, T_e, T_r; };
inline constexpr std::array<Region, 3> regions = {{{1001, 1.0, 0.3, 0.001, 0.0, 0.0, 0.0, 0.1, 0.1}, {1000, 1.0, 0.3, 0.001, 0.0, 0.0, 0.0, 0.1, 0.1}, {7777, 1.0, 0.3, 10000.0, 0.0, 0.0, 0.0, 0.83, 0.83}}};
// region index per (x_div, y_div, z_div), x-major
inline constexpr std::array<int, 54> regionTable = {{0, 2, 1, 2, 1, 2, 0, 1, 1, 1, 1, 2, 0, 2, 2, 2, 2, 2, 0, 1, 1, 1, 1, 2, 0, 1, 1, 1, 1, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2}};
inline constexpr int regionIndexAt(std::size_t ix, std::size_t iy, std::size_t iz)
{ return regionTable[(ix * yDiv.size() + iy) * zDiv.size() + iz]; }
} // namespace BransonDeck
#endif
