#!/usr/bin/env python3
"""Emit BransonDeck.hpp from a Branson XML input deck.

The point is fidelity: the STORM port and Branson must run the same geometry,
the same material constants and the same timestep, so both read one source of
truth instead of a hand-transcribed copy.  Branson's units (keV, cm, shake,
jerk) are kept verbatim here; main.cpp converts to cgs.

Usage: generate_deck_header.py <deck.xml> [output.hpp]
"""
import sys
import xml.etree.ElementTree as ET


def divisions(spatial, axis):
    out = []
    for d in spatial.findall(f"{axis}_division"):
        out.append((float(d.findtext(f"{axis}_start")),
                    float(d.findtext(f"{axis}_end")),
                    int(d.findtext(f"n_{axis}_cells"))))
    return out


def main():
    deck = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else "BransonDeck.hpp"
    root = ET.parse(deck).getroot()
    common = root.find("common")
    spatial = root.find("spatial")

    xd, yd, zd = (divisions(spatial, a) for a in "xyz")
    nx, ny, nz = (sum(d[2] for d in ds) for ds in (xd, yd, zd))

    # MadCart is uniform in y and z; verify the deck is uniform in all three so
    # the ported mesh is cell-for-cell identical rather than merely similar.
    widths = set()
    for ds in (xd, yd, zd):
        for lo, hi, n in ds:
            widths.add(round((hi - lo) / n, 12))
    if len(widths) != 1:
        sys.exit(f"deck is not uniformly spaced: cell widths {sorted(widths)}")
    h = widths.pop()

    # region_map is a 3-index table over division indices, not cells.
    table = {}
    for rm in spatial.findall("region_map"):
        key = (int(rm.findtext("x_div_ID")), int(rm.findtext("y_div_ID")), int(rm.findtext("z_div_ID")))
        table[key] = int(rm.findtext("region_ID"))
    expected = len(xd) * len(yd) * len(zd)
    if len(table) != expected:
        sys.exit(f"region_map has {len(table)} entries, expected {expected}")

    regions = []
    for r in root.find("regions").findall("region"):
        regions.append(dict(
            ID=int(r.findtext("ID")),
            density=float(r.findtext("density")),
            CV=float(r.findtext("CV")),
            opacA=float(r.findtext("opacA")),
            opacB=float(r.findtext("opacB")),
            opacC=float(r.findtext("opacC")),
            opacS=float(r.findtext("opacS")),
            T_e=float(r.findtext("initial_T_e")),
            T_r=float(r.findtext("initial_T_r"))))
    ids = [r["ID"] for r in regions]

    def cpp_div(ds):
        return ", ".join(f"{{{lo!r}, {hi!r}, {n}}}" for lo, hi, n in ds)

    # Flattened x-major so the C++ side indexes [ix][iy][iz] without a map.
    flat = []
    for ix in range(len(xd)):
        for iy in range(len(yd)):
            for iz in range(len(zd)):
                flat.append(ids.index(table[(ix, iy, iz)]))

    L = []
    L.append("// GENERATED by generate_deck_header.py -- do not edit.")
    L.append(f"// Source deck: {deck}")
    L.append("#ifndef STORM_BRANSON_DECK_HPP")
    L.append("#define STORM_BRANSON_DECK_HPP")
    L.append("#include <array>")
    L.append("#include <cstddef>")
    L.append("namespace BransonDeck {")
    L.append("// Branson units: cm, keV, shake (1e-8 s), jerk (1e16 erg).")
    L.append(f"inline constexpr std::size_t nx = {nx}, ny = {ny}, nz = {nz};")
    L.append(f"inline constexpr double cellWidth = {h!r};")
    L.append(f"inline constexpr double xLo = {xd[0][0]!r}, xHi = {xd[-1][1]!r};")
    L.append(f"inline constexpr double yLo = {yd[0][0]!r}, yHi = {yd[-1][1]!r};")
    L.append(f"inline constexpr double zLo = {zd[0][0]!r}, zHi = {zd[-1][1]!r};")
    L.append(f"inline constexpr double dtShakes = {float(common.findtext('dt_start'))!r};")
    L.append(f"inline constexpr double tStopShakes = {float(common.findtext('t_stop'))!r};")
    L.append(f"inline constexpr double tStartShakes = {float(common.findtext('t_start'))!r};")
    L.append(f"inline constexpr long long photons = {int(common.findtext('photons'))};")
    L.append("struct Division { double lo, hi; std::size_t cells; };")
    for name, ds in (("xDiv", xd), ("yDiv", yd), ("zDiv", zd)):
        L.append(f"inline constexpr std::array<Division, {len(ds)}> {name} = {{{{{cpp_div(ds)}}}}};")
    L.append("struct Region { int id; double density, CV, opacA, opacB, opacC, opacS, T_e, T_r; };")
    reg = ", ".join("{{{}, {!r}, {!r}, {!r}, {!r}, {!r}, {!r}, {!r}, {!r}}}".format(
        r["ID"], r["density"], r["CV"], r["opacA"], r["opacB"], r["opacC"], r["opacS"], r["T_e"], r["T_r"])
        for r in regions)
    L.append(f"inline constexpr std::array<Region, {len(regions)}> regions = {{{{{reg}}}}};")
    L.append(f"// region index per (x_div, y_div, z_div), x-major")
    L.append(f"inline constexpr std::array<int, {len(flat)}> regionTable = {{{{{', '.join(map(str, flat))}}}}};")
    L.append("inline constexpr int regionIndexAt(std::size_t ix, std::size_t iy, std::size_t iz)")
    L.append("{ return regionTable[(ix * yDiv.size() + iy) * zDiv.size() + iz]; }")
    L.append("} // namespace BransonDeck")
    L.append("#endif")
    open(out_path, "w").write("\n".join(L) + "\n")
    print(f"{out_path}: {nx}x{ny}x{nz} = {nx*ny*nz} cells, width {h}, "
          f"{len(regions)} regions, dt={common.findtext('dt_start')} sh")


main()
